apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      vllm:
        port: 8001
        expose:
          default: true
        exposedPort: 8000
        protocol: TCP
      cllm:
        port: 8081
        expose:
          default: true
        exposedPort: 8080
        protocol: TCP
