apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  labels:
    app.kubernetes.io/name: vllm
    monitoring.coreos.com/instance: prometheus
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - vllm
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
