apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - components.yaml
  - source.yaml
#  - listeners/flux-system.yaml
#  - listeners/nvidia-plugin.yaml
#  - listeners/traefik.yaml
#  - listeners/vllm.yaml
#  - listeners/cllm.yaml
#  - listeners/prometheus-operator.yaml
#  - listeners/prometheus.yaml
