apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vllm
  namespace: vllm
spec:
  entryPoints:
    - vllm
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: vllm
          port: 8000
