service:
  type: NodePort
  nodePort: 30081

opencost:
  exporter:
    defaultClusterId: k3s-local
  customPricing:
    enabled: true
    provider: custom
    createConfigmap: true
    costModel:
      description: Local K3s single-node pricing.
      CPU: 0.03
      spotCPU: 0.03
      RAM: 0.004
      spotRAM: 0.004
      GPU: 0.35
      storage: 0.0001
      zoneNetworkEgress: 0.00
      regionNetworkEgress: 0.00
      internetNetworkEgress: 0.00
  metrics:
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: monitoring
  prometheus:
    internal:
      enabled: false
    external:
      enabled: true
      url: http://monitoring-prometheus.monitoring.svc:9090
