apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cllm-storage
  namespace: cllm
  labels:
    app.kubernetes.io/name: cllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
